version: "3.9"

services:
  scan-cash-api:
    container_name: ScanCashAPI
    restart: always
    build:
      context: ScanCashAPI
    ports:
      - "5000:5000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
